[MINOR] Check Coinbot status and recover Open trades by status and symbol
Global-Financial-Automation/orchestrator pull request #4
Opened 2023-02-19 01:08 UTC by angelavortega

- Orchestrator recieves regular messages from each coinbot with their status and sends it to Botmanager
- New callBackFunction to recover trades by status and symbol from the tradesByStrategy collection

Missing:
- When there is an error in a Coinbot, store the message in the Database

2023-02-22 21:18 UTC, yamf0 requested changes

2023-02-22 21:18 UTC, yamf0 commented on src/dao/tradesDao.js
> +    static async getTradesByStatusSymbol(status, symbol) {
Maybe get rid of this one

2023-02-22 21:47 UTC, angelavortega commented on src/dao/tradesDao.js
> +    static async getTradesByStatusSymbol(status, symbol) {
done

2023-02-23 00:47 UTC, yamf0 approved these changes

2023-02-23 00:47 UTC, merged